### PR TITLE
 Allow conversations to continue across tabs 

### PR DESCRIPTION
**Pull request by dankadmin**
As per Issue #1, added `BroadcastChannel` and a promise to attempt to allow conversations to continue across different tabs and windows. The result is that new conversations begin with the state from existing tabs, if any exist, and an update in one tab updates all open tabs using the same localStorage.

A BroadcastChannel is added so that the state may be shared across all tabs. Each time the state is saved, it is broadcast to all channels.

A listener is also added so that any time a value is added to and immediately removed from `watson_bot_request_state` on localStorage, the sate is saved, forcing the broadcast. During the initial creation of the chat window, `componentDidMount`, before sending the initial message, the new window makes an entry in localStorage to request the state and waits for 250ms. If a broadcast is made in that time, it takes the initial state from that broadcast. Otherwise, it proceeds to send the initial message. Finally, the BroadcastChannel is set to listen and update the state on all future broadcasts.

The second `this.sendMessage()` was removed from `componentDidUpdate` because it seems redundant to the one from `componentDidMount` and it seems to cause issues in Chrome when there is a delay.

Ref #1

### CODE REVIEW

**Comment by cyrilrudenko** [comment]
Hi @dankadmin. Thank you for your contribution.
Unfortunately we can't use`BroadcastChannel` at the moment, because it's not supported by Edge and Safary (https://caniuse.com/#feat=broadcastchannel)

**Comment by dankadmin** [comment]
Thank you. I'm adding a shim which seems to add support for those browsers and some other clients.

**Comment by dankadmin** [comment]
The changes were tested with Firefox, Chrome, Edge, and Safari. Let me know if there are any other issues or recommendations for this. Thank you for considering this update.

**Comment by cyrilrudenko** [comment]
Thank you, @dankadmin. 
We will merge your contribution into our master repo, 
all changes will appear here (on github) with the next plugin release.

**Comment by cyrilrudenko** [comment]
Thank you, @dankadmin.
I've merged your contribution here on GitHub,
also these changes will be available on WordPress Plugins with the next plug-in release.

**Pull request merged**
